### ISSUE TITLE
Support for AR9271

### ISSUE THREAD

**Issue by Lyton505** [rsa9000/atheepmgr#5] opened 2022-08-27 08:48 UTC
I am trying to read the EEPROM for an ALfa AWUS036NHA wifi adapter. 
The output of _lsusb_ is:

`Bus 001 Device 006: ID 0cf3:9271 Qualcomm Atheros Communications AR9271 802.11n`

I then try to run this tool with these arguments. The alfa card is wlan1

`./atheepmgr -t AR9271 -D wlan1`

In which case I get the output "_**Unknown EEPROM map type or chip name or chip Id: AR9271**_"

Is this card supported?

**Comment by rsa9000** [comment] 2022-08-27 10:54
Hello Lyton,

I have never tested the utility against any USB chips, but it should most likely work if a proper "eeprom map" is specified. For AR9271, according to the ath9k driver, the proper eeprom map is AR9285 (aka eeprom 4k). Try this command for your device:

`$ ./atheepmgr -t 9285 -vv -D wlan1`

Anyway, if the utility fails to read the EEPROM on its own, you can always read the EEPROM contents using the ath9k driver debug interface and then parse the extracted data:

`$ cat /sys/kernel/debug/ieee80211/phyX/ath9k/eeprom > /tmp/eep.bin`
`$ ./atheepmgr -t 9285 -F /tmp/eep.bin`

**Comment by Lyton505** [comment] 2022-08-27 12:04
Thank you. I  can read the eeprom contents via 

`root@gecko# cat /sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom `

The driver seems to be ath9k_htc instead of ath9k. I am not sure if that makes any difference at all.

`$ ./atheepmgr -t 9285 -F /tmp/eep.bin` gives the output **_Invalid EEPROM Magic 0x2020, expected 0xa55a
EEPROM check failed_**

**Comment by rsa9000** [comment] 2022-08-27 14:09
> Thank you. I can read the eeprom contents via
> 
> `root@gecko# cat /sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom `

Yeah, I forgot that raw eeprom debugfs interface is an OpenWrt specific feature. But _base_epprom_ also provides some useful information.

> The driver seems to be ath9k_htc instead of ath9k. I am not sure if that makes any difference at all.

These are almost the same driver, the difference is only in a device bus. So almost no difference.

> `$ ./atheepmgr -t 9285 -F /tmp/eep.bin` gives the output **_Invalid EEPROM Magic 0x2020, expected 0xa55a EEPROM check failed_**

Can you run the utility in verbose mode with the _-vv_ option and share the output?

**Comment by rsa9000** [comment] 2022-09-13 19:56
I will close the issue. Feel free to reopen it if needed.

**Closed as completed** 2022-09-13 19:56 UTC

**Comment by ElongatedTusk** [comment] 2023-02-06 07:57
> I will close the issue. Feel free to reopen it if needed. @rsa9000 

New person with same exact USB adapter (Alfa AWUS036NHA) and driver (ath9k_htc). I've reproduced this thread and ran `./atheepmgr -vv -t 9285 -F /tmp/eep.bin` where /tmp/eep.bin is the contents of /sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom. Here is the output: 
```
confile: file data length is 0x02af (687) bytes, emulate 0x0800 bytes (2 KB, 16 kbit) EEPROM IC
EEPROM access ops: use connector's ops
OTP access ops: use connector's ops
Try to load data from EEPROM
Got byteswapped Little-endian EEPROM data
Toggle EEPROM I/O byteswap compensation
Invalid EEPROM Magic 0x2020, expected 0xa55a
EEPROM check failed
```

**Comment by rsa9000** [comment] 2023-02-06 13:25
`/sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom` - contains plaintext data, what are parsed and formatted by the driver itself. You could check its contents just with cat.

**Comment by ElongatedTusk** [comment] 2023-02-06 14:01
> `/sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom` - contains plaintext data, what are parsed and formatted by the driver itself. You could check its contents just with cat.

I followed every step in this thread up to that point, including the command you said to use: `cat /sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom > /tmp/eep.bin` followed by `./atheepmgr -vv -t 9285 -F /tmp/eep.bin` with the verbose flag, as you requested here https://github.com/rsa9000/atheepmgr/issues/5#issuecomment-1229199435

which is what the output i posted is from. I'm picking up from exactly where the first user left off and am no closer to being able to identify or read EEPROM data from the ath9k_htc driver with atheepmgr.

Edit: If this helps at all, here is the output of `cat /sys/kernel/debug/ieee80211/phy2/ath9k_htc/base_eeprom`:

```
       Major Version :         14
       Minor Version :         15
            Checksum :      39387
              Length :        376
          RegDomain1 :      33594
          RegDomain2 :          0
             TX Mask :          1
             RX Mask :          1
          Allow 5GHz :          0
          Allow 2GHz :          1
   Disable 2GHz HT20 :          0
   Disable 2GHz HT40 :          0
   Disable 5Ghz HT20 :          0
   Disable 5Ghz HT40 :          0
          Big Endian :          0
   Cal Bin Major Ver :          0
   Cal Bin Minor Ver :          8
       Cal Bin Build :        131
        TX Gain type :          1

```
With the last line (MAC Address) redacted.

**Comment by rsa9000** [comment] 2023-02-06 15:28
Ok. Let's start from the beginning. atheepmgr woks only with the binary calibration/configuration data. It can be already extracted binary blob or utility able to extract data itself in some cases. As I stated at the beginning of the thread, atheepmgr is never tested against USB dongles. So I do not know for sure either it will be able to extract data or not.

ath9k driver extracts EEPROM contents and parses it for proper NIC configuration. But ath9k in stock never exported raw binary data to user space. ath9k exports only some bits of already parsed information via:

`/sys/kernel/debug/ieee80211/phyX/ath9k_htc/base_eeprom`

On other hand the OpenWrt firmware (Linux distro) contains a special hack (patch) for the ath9k driver, what creates additional debugfs file for raw EEPROM contents export. This is:

`/sys/kernel/debug/ieee80211/phyX/ath9k_htc/eeprom`

As you can see this is a different file and, as is noted above, this file available only on OpenWrt based routers.

Now you have at least two options. Either analyze plaintext contents of `base_eeprom` to get required information or try to extract binary EEPROM data and feed it to atheepmgr.

But what would you like to do? I mean despite of any particular utility use. What would like to reach? Do you need some particular parameter value or something like that? With this key question answered, we can go ahead and choose a proper tool for its implementation.

**Comment by ElongatedTusk** [comment] 2023-02-06 16:10
Thank you for clearing that up for me, and forgive me, I have 0 experience editing, reading, etc EEPROM values on a driver. 

I'm trying to change the regdom value to a particular location, as the current value in the driver overrides my kernel and user space configurations in modprobe.d, crda, and iw reg set command. The configurations take affect on my internal wifi card, but not the Alfa AWUS036NHA USB wifi adapter. Here's the output from `dmesg | grep ath`:
```
[ 7081.190578] usb 3-1: ath9k_htc: USB layer deinitialized
[ 9700.378675] usb 3-1: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[ 9700.664315] usb 3-1: ath9k_htc: Transferred FW: ath9k_htc/htc_9271-1.4.0.fw, size: 51008
[ 9700.917457] ath9k_htc 3-1:1.0: ath9k_htc: HTC initialized with 33 credits
[ 9701.189836] ath9k_htc 3-1:1.0: ath9k_htc: FW Version: 1.4
[ 9701.189844] ath9k_htc 3-1:1.0: FW RMW support: On
[ 9701.189847] ath: EEPROM regdomain: 0x833a
[ 9701.189850] ath: EEPROM indicates we should expect a country code
[ 9701.189853] ath: doing EEPROM country->regdmn map search
[ 9701.189854] ath: country maps to regdmn code: 0x37
[ 9701.189856] ath: Country alpha2 being used: GB
[ 9701.189858] ath: Regpair used: 0x37
[33387.241250] ath: phy2: Failed to wakeup in 500us
[33387.251661] ath: phy2: Failed to wakeup in 500us
[33387.347633] usb 3-1: ath9k_htc: USB layer deinitialized
[37766.276732] usb 3-2: ath9k_htc: Firmware ath9k_htc/htc_9271-1.4.0.fw requested
[37766.566978] usb 3-2: ath9k_htc: Transferred FW: ath9k_htc/htc_9271-1.4.0.fw, size: 51008
[37766.820569] ath9k_htc 3-2:1.0: ath9k_htc: HTC initialized with 33 credits
[37767.122531] ath9k_htc 3-2:1.0: ath9k_htc: FW Version: 1.4
[37767.122543] ath9k_htc 3-2:1.0: FW RMW support: On
[37767.122548] ath: EEPROM regdomain: 0x833a
[37767.122550] ath: EEPROM indicates we should expect a country code
[37767.122553] ath: doing EEPROM country->regdmn map search
[37767.122555] ath: country maps to regdmn code: 0x37
[37767.122557] ath: Country alpha2 being used: GB
[37767.122559] ath: Regpair used: 0x37
```
As far as I can tell, the ath9k_htc driver is checking the regdom value, which executes a "regdmn map search" function, which always defaults to GB (Great Britain). I'd like to edit that value to be my region, and not GB. 

The 2 deinitialized lines are from me unplugging the adapter and plugging it back in. If nothing else, it demonstrates that it consistently behaves this way. This is the same behavior no matter the USB port and no matter the regdom configurations on my system.

**Comment by rsa9000** [comment] 2023-02-07 16:46
Thank you for clarifying the case. But I should say sorry because I can not help with the RegDomain change. At the moment, atheepmgr does not support regdomain modification at all. The regdomain parameter is just a tip of the iceberg of the correct radioemission configuration. So I assume that arbitrary changing the regdomain, especially such a country specific regdomain without properly reviewing of the other params, is a quite dangerous path. A path that can lead to unintended, but still annoying interference with other radio equipment.

But I would like to ask what is the purpose of the regdomain change? Is it possible to achieve the same goal in a less intrusive way? Would you like to "open" some channels that are not allowed in GB but are available in your location? Or are you trying to solve some issues with a regdomain interference between two installed cards?

If the case can be solved in software, then I suggest you to ask for assistance in the linux-wireless mailing list and properly describe the issue. If this is already known, then perhaps someone has already fond a solution, if your issue is new, then the driver/stack should be fixed to avoid bothering with hardware hacks.

**Comment by ElongatedTusk** [comment] 2023-02-08 07:44
> But I would like to ask what is the purpose of the regdomain change? Is it possible to achieve the same goal in a less intrusive way? Would you like to "open" some channels that are not allowed in GB but are available in your location?

Quite a peculiar issue. The fact that the ath9k_htc driver is making a regdom call to a function which sets it to Great Britain isn't an issue for me in theory, because GB has the channels I need (12 and 13) enabled, and in my region those channels are also enabled per local laws. In practice, however, it is a different story. I cannot pinpoint what is triggering the behavior, but occasionally, while trying to create an access point or monitor traffic on a channel above 11, the ath9k_htc driver behaves as if it is set to a North American regdom (where channels 12 and 13 are disabled). 

The above behavior tends to start once i change my adapter to monitor mode, but not consistently. I've set the regdom through every possible method I can in the kernel and user-space; but alas, it still defaults to GB (with the odd behavior) because the EEPROM regdom value over-rides any software configuration. I think the map search function it is calling is the culprit, which is why I'd like to explicitly set the regdom in the driver. Quite frankly, I don't care if it is set to Great Britain, so long as it consistently behaves as such (not disabling channel 12 and 13 seemingly at random).

Anyway, you've provided useful information and given me needed closure to save me time from pursuing this avenue any longer than I need to. I'll direct my issue to a more appropriate forum, and I apologize for the unrelated nature of my issue. Thank you for taking the time to help me regardless, I appreciate it. Take care.

**Comment by akostadinov** [comment] 2024-04-26 21:54
@rsa9000 , I think only the regulatory domain change is needed to be changed because kernel already sets regulatory restrictions based on what it sees in eeprom. So if it is wrong, wrong restrictions are applied. OpenWRT carries some driver patches to override that. But these are not in any other distro.

PS I'm using  a mini pcie card annd eeprom is dumped successfully, just don't know how to update it, especially regenerate checksum

**Comment by rsa9000** [comment] 2024-06-01 12:06
@akostadinov, it depends on how someone defines "wrong". Playing with radio params could easily introduces transmission issues, which will create problems to other RF spectrum users. As for me, the best way to deal with an unusual regdomain is to return the equipment to the store. I do not remember anyone reworking their 110V kitchen appliance to 220V :)

On another hand, the utility contains everything required to implement the regdomain rewriting feature, including checksum recalculation. Just be careful and keep in view other spectrum users.

**Comment by akostadinov** [comment] 2024-06-04 17:02
Changing equipment may work for new equipment but if you try to use some old system, not so. Also if you live in a smaller country a lot of equipment is imported from all sorts of regions. Eventually it turned out I had another card lying that worked better. Just I lost too much time with this one.

I didn't find any instructions about fixing checksum after updating the file. Maybe you did on purpose to allow only somebody with sufficient programming skills to do it. Although knowing C doesn't necessary mean the person is responsible in their actions. I'm not a C programmer, I didn't spot that the project had such capabilities. Maybe if I knew, I could have discovered it, but I didn't try. Just assumed it didn't because it is not documented.

I think it's better to have a clue in documentation, some pointer about that. But anyway, I have no use case for it at the moment.

**Comment by rsa9000** [comment] 2024-06-04 22:11
Hi @akostadinov, thank you for sharing the case details. I agree with you. An equipment that is incapable to fully operate in a locally allocated spectrum is annoying and discouraging. In the same time let me share my concerns. Sorry if I'm going to say obvious things.

Besides neighbors' WiFi routers, the most obvious users of the 5GHz band are weather radars. Here I found a nice image from a radar that was mangled by a WiFi transmission: https://www.theregister.com/2014/05/20/getting_wifi_glitches_out_of_weather_radar/ Outside the WiFi bands are surrounded by other legitimate users like cellular networks, public safety and emergency service organizations. Suddenly, power amplifiers and other radio equipment components tend to produce out of band signals, when operated outside of a designed point. Here I found another one nice looking image that demonstrates how out of band signal could be found far away from a desired frequency: https://www.5gtechnologyworld.com/simulate-test-and-verify-to-solve-5g-rf-design-problems/ And WiFi equipment is not famous for their output filtering.

The famous OpenWrt patch for RegDomain was created as a response to the careless behaviour of some vendors that break Atheros recommendation to properly specify a RegDomain value inside the calibration data. The patch functionality is based on a simple assumption that a WiFi router purchased from a local store is properly designed and calibrated for the local frequency allocation. Thus, forcing OpenWrt users to follow Atheros recommendation that have already been broken by a vendor will unnecessarily forbid end users from using their fully compliant equipment. And OpenWrt firmware lifts the Atheros limitations while still follows local rules specified in regdb.

I would like to highlight the word "router". The patch mainly considers WiFi routers. And in this context it has a high probability to match the reality. A probability is still a probability, and the wireless stack serves not only routers, but also laptop cards, usb dongles, and so on. Taking all this into consideration, the patch has not been upstreamed. And it is unlikely that the patch will be integrated into the mainline kernel or any other general purpose Linux distribution.

I share the same concerns and assume that an easily accessible functionality for the RegDomain overwriting will become the Pandora's Box. Good intentions that lead to an unpleasant mess.

**Comment by rsa9000** [comment] 2024-06-04 22:29
Back to the code. I did not hide something or obfuscate it. It is designed to be clear for anyone familiar with the radio equipment calibration. Yes, the utility is targeted to an engineering audience. I agree that the C programing skill does not make you a radio engineer. At the same time, I believe it implies some common engineering sense that allows you to study and predict possible outcomes. And I hope that this will serve as a safety barrier between mess and respectful spectrum usage.
